[package]
name = "authenticame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.16"
envconfig = "0.10.0"
serde = { version = "1.0.145", features = ["derive", "serde_derive"] }
tokio = { version = "1.21.1", features = ["full"] }
