name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-check
      uses: actions-rs/cargo@v1.0.1
      with:
        command: check
        toolchain: stable
    - name: rust-build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        toolchain: stable
        args: --verbose
    - name: rust-test
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        toolchain: stable
        args: --verbose
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.0
